title: Ritvik Food
description: A personal culinary archive—cooked, baked, mixed, and loved.
owner: Ritvik Kharkar
first_published: 2017
email: ritvikmathematics@gmail.com
url: "https://ritvikfood.com"
baseurl: ""
timezone: America/Los_Angeles
markdown: kramdown
sass:
  style: compressed
exclude:
  - README.txt
